version: '3.8'

services:
 

  nextjs-app:
    build: .
    ports:
      - "3001:3000"
    environment:
      # Load environment variables from .env.local file in the root
      - "ENV_FILE_LOCATION=./.env.local"
    command: npm run start
    restart: always
