# Base image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# # Define arguments
# ARG NEXTAUTH_SECRET
# ARG NEXT_PUBLIC_API
# ARG NEXTAUTH_URL
# ARG NEXT_PUBLIC_API_URL
# ARG NEXT_PUBLIC_PROFILE_URL
# ARG NEXT_PUBLIC_FIELDMANAGER_URL
# ARG NEXT_PUBLIC_FIELDMANAGER_URL_DEVELOPER
# ARG ACCESS_TOKEN_EXPIRY
# ARG JWT_ALGORITHM

# # Convert arguments to environment variables
# ENV NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
# ENV NEXT_PUBLIC_API=${NEXT_PUBLIC_API}
# ENV NEXTAUTH_URL=${NEXTAUTH_URL}
# ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
# ENV NEXT_PUBLIC_PROFILE_URL=${NEXT_PUBLIC_PROFILE_URL}
# ENV NEXT_PUBLIC_FIELDMANAGER_URL=${NEXT_PUBLIC_FIELDMANAGER_URL}
# ENV NEXT_PUBLIC_FIELDMANAGER_URL_DEVELOPER=${NEXT_PUBLIC_FIELDMANAGER_URL_DEVELOPER}
# ENV ACCESS_TOKEN_EXPIRY=${ACCESS_TOKEN_EXPIRY}
# ENV JWT_ALGORITHM=${JWT_ALGORITHM}

COPY package*.json ./

# Install Tailwind CSS
RUN npm install 

# Copy the entire app to the container
COPY . .

# Build the app
RUN npm run build
EXPOSE 3000

# Specify the command to run when the container starts
CMD ["npm", "start"]