env: flex
runtime: custom
env_variables:
  KEYCLOAK_ADMIN: 'admin'
  KEYCLOAK_ADMIN_PASSWORD: 'admin'
  KC_DB_URL_HOST: 'ep-tight-bonus-209614-pooler.us-east-1.postgres.vercel-storage.com'
  KC_DB: 'postgres'
  KC_DB_USERNAME: 'default'
  KC_DB_PASSWORD: 'qb0wRci3QsYX'
  KC_DB_URL_PORT: '5432'
  KC_HOSTNAME: 'https://table-tennis-404218.ey.r.appspot.com/'
